# Generated by Django 5.2.8 on 2025-11-10 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('korisnicko_ime', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('aktivan', models.BooleanField(default=True)),
                ('registriran_od', models.DateTimeField(auto_now_add=True)),
                ('password_hash', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StatusSastanka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Uloga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_uloge', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sastanak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=200)),
                ('napravljen_od', models.DateTimeField()),
                ('lokacija', models.CharField(max_length=200)),
                ('datum_vrijeme', models.DateTimeField()),
                ('sazetak', models.TextField(blank=True, null=True)),
                ('id_korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.korisnik')),
                ('id_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.statussastanka')),
            ],
        ),
        migrations.CreateModel(
            name='Obavijesti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poruka', models.TextField()),
                ('poslano_u', models.DateTimeField(blank=True, null=True)),
                ('status_mail', models.CharField(blank=True, max_length=30, null=True)),
                ('id_sastanak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sastanak')),
            ],
        ),
        migrations.CreateModel(
            name='Sudjeluje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrijeme_potvrde', models.DateTimeField(blank=True, null=True)),
                ('potvrda', models.BooleanField(default=False)),
                ('id_korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.korisnik')),
                ('id_sastanak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sastanak')),
            ],
            options={
                'unique_together': {('id_korisnik', 'id_sastanak')},
            },
        ),
        migrations.CreateModel(
            name='TockeDnevReda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj_tocke', models.IntegerField()),
                ('naziv', models.CharField(max_length=200)),
                ('opis', models.TextField(blank=True, null=True)),
                ('pravni_ucinak', models.BooleanField(default=False)),
                ('id_sastanak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sastanak')),
            ],
        ),
        migrations.CreateModel(
            name='Rasprava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_StanBlog', models.CharField(max_length=255)),
                ('id_tocke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tockednevreda')),
            ],
        ),
        migrations.AddField(
            model_name='korisnik',
            name='id_uloge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.uloga'),
        ),
        migrations.CreateModel(
            name='Zakljucak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.TextField()),
                ('status', models.CharField(max_length=30)),
                ('unesen_u', models.DateTimeField(auto_now_add=True)),
                ('id_korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.korisnik')),
                ('id_tocke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tockednevreda')),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
