# Generated by Django 5.2.8 on 2026-01-14 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_korisnik_statussastanka_uloga_sastanak_obavijesti_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='korisnik',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='obavijesti',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rasprava',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sastanak',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='statussastanka',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sudjeluje',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tockednevreda',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='uloga',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='zakljucak',
            options={'managed': False},
        ),
    ]
