# Generated by Django 5.2.8 on 2026-01-14 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_korisnik_options_alter_obavijesti_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='korisnik',
            table='korisnik',
        ),
        migrations.AlterModelTable(
            name='obavijesti',
            table='obavijesti',
        ),
        migrations.AlterModelTable(
            name='rasprava',
            table='rasprava',
        ),
        migrations.AlterModelTable(
            name='sastanak',
            table='sastanak',
        ),
        migrations.AlterModelTable(
            name='statussastanka',
            table='status_sastanka',
        ),
        migrations.AlterModelTable(
            name='sudjeluje',
            table='sudjeluje',
        ),
        migrations.AlterModelTable(
            name='tockednevreda',
            table='tockednevreda',
        ),
        migrations.AlterModelTable(
            name='uloga',
            table='uloga',
        ),
        migrations.AlterModelTable(
            name='zakljucak',
            table='zakljucak',
        ),
    ]
