# Generated by Django 5.2.8 on 2026-01-14 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_korisnik_table_alter_obavijesti_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tockednevreda',
            options={'managed': True},
        ),
    ]
