# Generated by Django 5.2.8 on 2026-01-17 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_tockednevreda_glasanje_poveznica_diskusije'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tockednevreda',
            options={'managed': False},
        ),
    ]
